name: Sample Action with Email

on:
  push:
    branches:
      - main  # Triggers on push to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Specifies the runner environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This checks out the repository's code

      - name: 23f1002489@ds.study.iitm.ac.in
        run: echo "Hello, world!"  # This step will print 'Hello, world!' to the log
